name: "Test Matrix"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account: 
          - { email: "test1@gmail.com", token: "xxx" }
          - { email: "test2@gmail.com", token: "yyy" }
    steps:
      - run: echo "处理账号 ${{ matrix.account.email }}"
